modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/LYIVX/LYIVXsCore/issues"

[[mods]]
modId = "ls_core"
version = "1.1.5"
displayName = "LYIVX's Core"
authors = "LYIVX"
description = "A Core Mod For LYIVX's Mods"
displayURL = "https://modrinth.com/mod/lyivxs-core"


[[dependencies.ls_core]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ls_core]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ls_core]]
modId = "resourcefullib"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ls_core]]
modId = "architectury"
type = "required"
versionRange = "[*,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "LYIVXsCore-common.mixins.json"
